.TH "matchstring.cpp" 3 "Thu May 26 2016" "Version 2.0cpp" "Matchstring" \" -*- nroff -*-
.ad l
.nh
.SH NAME
matchstring.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBstrmatch\fP (string str1, string str2)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool strmatch (string str1, string str2)"
This is a function comparing two strings one containing wildcards '*' and '?' String 1 is the input string while string 2 is the reference string\&. Certain exceptions can be added to the program though\&. Output 1 implies matching strings whereas 0 implies mismatch\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Matchstring from the source code\&.
