.TH "spiral.c" 3 "Thu May 26 2016" "Version C" "ReverseSpiral" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spiral.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBrevspiral\fP (int n, int mat[n][n])"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SS "void revspiral (int n, int mat[n][n])"

.SH "Author"
.PP 
Generated automatically by Doxygen for ReverseSpiral from the source code\&.
